# Generated by Django 5.0.2 on 2024-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianform',
            name='Phone_number',
            field=models.IntegerField(),
        ),
    ]
